#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$:.unshift(lib_path) if !$:.include?(lib_path)
require 'module_one_final_project/cli'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  ModuleOneFinalProject::CLI.start
rescue ModuleOneFinalProject::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
